apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: prometheus-operator
    version: 8.12.2
  values:
    prometheus:
      prometheusSpec:
        portName: http
        storageSpec: 
          volumeClaimTemplate:
            spec:
              storageClassName: default
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 2Gi
        thanos:
          baseImage: quay.io/thanos/thanos
          version: v0.10.1
          objectStorageConfig:
            key: thanos.yaml
            name: thanos-objstore-config
      service:
        additionalPorts:
          - name: thanos-grpc
            port: 10901
            targetPort: 10901
          - name: thanos-http
            port: 10902
            targetPort: 10902
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: istio
        hosts:
          - prometheus.tools.com
    alertmanager:
      alertmanagerSpec:
        portName: http
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: default
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 2Gi
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: istio
        hosts:
          - alertmanager.tools.com
    grafana:
      service:
        portName: http
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: istio
        hosts:
          - grafana.tools.com





