apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: prometheus-operator
    version: 8.12.2
  values:
    prometheus:
      prometheusSpec:
        storageSpec: 
          volumeClaimTemplate:
            spec:
              storageClassName: default
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 2Gi
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: istio
        hosts:
          - prometheus.tools.com
        # tls:
        #    - secretName: prometheus-general-tls
        #      hosts:
        #        - prometheus.tools.com
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: default
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 2Gi
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: istio
        hosts:
          - alertmanager.tools.com
    grafana:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: istio
        hosts:
          - grafana.tools.com





