apiVersion: velero.io/v1
kind: Schedule
metadata:
  creationTimestamp: null
  name: sealed-secrets-backup
  namespace: velero
spec:
  schedule: '@every 12h'
  template:
    hooks: {}
    includedNamespaces:
    - sealed-secrets
    ttl: 720h0m0s