# Default values for app.

replicaCount: 1
logLevel: info
version: "v1"
faults:
  delay: false
  error: false

service:
  port: 9898

image:
  repository: haisumb/helloworld
  tag: develop-20200302163321.48276268.dafc306
  pullPolicy: IfNotPresent


hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  cpu: 80
  memory: 512Mi

canary:
  enabled: false
  # Istio traffic policy tls can be DISABLE or ISTIO_MUTUAL
  istioTLS: DISABLE
  istioIngress:
    enabled: false
    # Istio ingress gateway name
    gateway: public-gateway.istio-system.svc.cluster.local
    # external host name eg. podinfo.example.com
    host:
  analysis:
    # schedule interval (default 60s)
    interval: 15s
    # max number of failed metric checks before rollback
    threshold: 10
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 5
  thresholds:
    # minimum req success rate (non 5xx responses)
    # percentage (0-100)
    successRate: 99
    # maximum req duration P99
    # milliseconds
    latency: 500
  loadtest:
    enabled: false
    # load tester address
    url: http://flagger-loadtester.default/
  helmtest:
    enabled: false
    # helm tester address
    url: http://flagger-helmtester-loadtester.kube-system/
  bluegreen:
    enabled: false
    iterations: 2
  confirm:
    rollback:
      status: halt
    promotion:
      enabled: false
      status: halt

resources:
  limits:
  requests:
    cpu: 50m
    memory: 32Mi

serviceAccount:
  # Specifies whether a service account should be created
  enabled: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

# Can disable istio by passing appropriate annotation
deployment:
  annotations:
    # sidecar.istio.io/inject: "false"


nodeSelector: {}

tolerations: []

affinity: {}

