---
# helm upgrade -i frontend flagger/podinfo \
# --namespace test \
# --set nameOverride=frontend \
# --set backend=http://backend.test:9898/echo \
# --set canary.enabled=true \
# --set canary.istioIngress.enabled=true \
# --set canary.istioIngress.gateway=public-gateway.istio-system.svc.cluster.local \
# --set canary.istioIngress.host=frontend.istio.example.com
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helloworld-canary
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:feature-canary-*
spec:
  releaseName: helloworld-canary
  chart:
    git: git@github.com:haisumb/aks-gitops-mvp-flux
    path: environments/staging/centralus/charts/generic
    ref: master
  values:
    image:
      repository: haisumb/helloworld
      tag: feature-canary-20200309150856.52344222.48b4886
    fullnameOverride: helloworld-canary
    nameOverride: helloworld-canary
    replicaCount: 3
    canary:
      enabled: true
      istioIngress:
        enabled: true
        gateway: public-gateway.istio-system.svc.cluster.local
        host: hello.example.com
