---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helloworld
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:develop-*
spec:
  releaseName: helloworld
  chart:
    git: git@github.com:haisumb/aks-gitops-mvp-flux
    path: environments/staging/centralus/charts/generic
    ref: master
  values:
    image:
      repository: haisumb/helloworld
      tag: develop-20200305164659.50235232.917d7f6
    nameOverride: helloworld
    replicaCount: 3
