---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helloworld-feature-bugfix
  namespace: default
  annotations:
    # important to set feature-bugfix-* here
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:feature-bugfix-*
spec:
  releaseName: helloworld-feature-bugfix
  chart:
    git: git@github.com:haisumb/aks-gitops-mvp-flux
    path: environments/staging/centralus/charts/generic
    ref: master
  rollback:
    # If set, will perform rollbacks for this release.
    enable: true
    # If set, will force resource update through delete/recreate if
    # needed.
    force: false
    # Prevent hooks from running during rollback.
    disableHooks: true
    # Time in seconds to wait for any individual Kubernetes operation.
    timeout: 300
    # If set, will wait until all Pods, PVCs, Services, and minimum
    # number of Pods of a Deployment are in a ready state before
    # marking the release as successful. It will wait for as long
    # as the set timeout.
    wait: true
  values:
    image:
      repository: haisumb/helloworld
      tag: feature-bugfix-a0a717e8fe5ab075ea7c06a4e9e0e13c2bcedcfd
    fullnameOverride: helloworld-feature-bugfix
    nameOverride: helloworld-feature-bugfix
    replicaCount: 1
    canary:
      enabled: true
      loadtest:
        enabled: true
      # Enable when we have helm tests
      helmtest:
        enabled: false
      istioIngress:
        enabled: true
        gateway: public-gateway.istio-system.svc.cluster.local
        host: feature-bugfix.helloworld.com
      bluegreen:
        enabled: false
      confirm:
        rollback:
          status: halt
        promotion:
          enabled: true
          status: halt
