---
# helm upgrade -i frontend flagger/podinfo \
# --namespace test \
# --set nameOverride=frontend \
# --set backend=http://backend.test:9898/echo \
# --set canary.enabled=true \
# --set canary.loadtest.enabled=true \
# --set canary.helmtest.enabled=true \
# --set canary.istioIngress.enabled=true \
# --set canary.istioIngress.gateway=public-gateway.istio-system.svc.cluster.local \
# --set canary.istioIngress.host=frontend.istio.example.com
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helloworld
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:feature-canary-*
spec:
  releaseName: helloworld
  chart:
    git: git@github.com:haisumb/aks-gitops-mvp-flux
    path: environments/staging/centralus/charts/generic
    ref: master
  values:
    image:
      repository: haisumb/helloworld
      tag: feature-canary-20200310173018.53117095.31b9245
    fullnameOverride: helloworld
    nameOverride: helloworld
    replicaCount: 2
    canary:
      enabled: true
      loadtest:
        enabled: true
      # Enable when we have helm tests
      helmtest:
        enabled: false
      istioIngress:
        enabled: true
        gateway: public-gateway.istio-system.svc.cluster.local
        host: helloworld.com
