---
# helm upgrade -i frontend flagger/podinfo \
# --namespace test \
# --set nameOverride=frontend \
# --set backend=http://backend.test:9898/echo \
# --set canary.enabled=true \
# --set canary.loadtest.enabled=true \
# --set canary.helmtest.enabled=true \
# --set canary.istioIngress.enabled=true \
# --set canary.istioIngress.gateway=public-gateway.istio-system.svc.cluster.local \
# --set canary.istioIngress.host=frontend.istio.example.com
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helloworld
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:feature-canary-*
spec:
  releaseName: helloworld
  chart:
    git: git@github.com:haisumb/aks-gitops-mvp-flux
    path: environments/staging/centralus/charts/generic
    ref: master
  rollback:
    # If set, will perform rollbacks for this release.
    enable: true
    # If set, will force resource update through delete/recreate if
    # needed.
    force: false
    # Prevent hooks from running during rollback.
    disableHooks: true
    # Time in seconds to wait for any individual Kubernetes operation.
    timeout: 300
    # If set, will wait until all Pods, PVCs, Services, and minimum
    # number of Pods of a Deployment are in a ready state before
    # marking the release as successful. It will wait for as long
    # as the set timeout.
    wait: true
  values:
    image:
      repository: haisumb/helloworld
      tag: feature-canary-20200317131415.57481209.eddba6c
    fullnameOverride: helloworld
    nameOverride: helloworld
    replicaCount: 2
    canary:
      enabled: true
      loadtest:
        enabled: true
      # Enable when we have helm tests
      helmtest:
        enabled: false
      istioIngress:
        enabled: true
        gateway: public-gateway.istio-system.svc.cluster.local
        host: helloworld.com
      bluegreen:
        enabled: false
      confirm:
        rollback:
          status: halt
        promotion:
          enabled: true
          status: approve
